# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Python Package CI

on:
  push:
    branches:
      - main  # Run on push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # Cache pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # If you use pyproject.toml with Poetry, use:
          # pip install poetry
          # poetry install --no-root
          # If you use pyproject.toml with Hatch, use:
          # pip install hatch
          # hatch env prune
          # hatch env restore
          # If you use requirements.txt:
          pip install -r requirements.txt
          pip install pytest pytest-cov # Install testing dependencies

      - name: Run tests with pytest
        run: |
          pytest --cov=auto --cov-report=xml
          ls
        env:
          PYTHONPATH: "${{ github.workspace }}/auto" # Ensure auto is on the PYTHONPATH for imports

